name: Fast Production Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Package and Push
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📦 Archive files
        run: zip -r deploy.zip . -x "*.git*" ".github/*" "README.md" ".gitignore"

      - name: 🚀 Upload Archive via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./public_html/ 
          include: 'deploy.zip'

      - name: ⚡ Trigger Server Unzip
        run: |
          curl -X POST https://tech-x.ro/deploy.php \
          -d "key=${{ secrets.DEPLOY_KEY }}"